// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	UserID      uuid.UUID `json:"user_id"`
	HashedToken string    `json:"hashed_token"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type Report struct {
	UserID            uuid.UUID      `json:"user_id"`
	ID                uuid.UUID      `json:"id"`
	ReportType        string         `json:"report_type"`
	OutputFilePath    sql.NullString `json:"output_file_path"`
	DownloadUrl       sql.NullString `json:"download_url"`
	DownloadExpiresAt sql.NullTime   `json:"download_expires_at"`
	ErrorMessage      sql.NullString `json:"error_message"`
	CreatedAt         time.Time      `json:"created_at"`
	StartedAt         sql.NullTime   `json:"started_at"`
	FailedAt          sql.NullTime   `json:"failed_at"`
	CompletedAt       sql.NullTime   `json:"completed_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
