// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, hashedToken string) error
	DeleteUserRefreshToken(ctx context.Context, arg DeleteUserRefreshTokenParams) error
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetRefreshToken(ctx context.Context, hashedToken string) (RefreshToken, error)
	GetTokenByPrimaryKey(ctx context.Context, arg GetTokenByPrimaryKeyParams) (RefreshToken, error)
	UpdateRefreshTokenExpiry(ctx context.Context, arg UpdateRefreshTokenExpiryParams) (RefreshToken, error)
}

var _ Querier = (*Queries)(nil)
